site_name: The Roadmap
repo_url: https://github.com/dariomtz/the-roadmap/
site_url: https://example.com/
theme:
  name: material 
nav:
  - Home: index.md
  - Data Strucutres: data_structures
markdown_extensions:
  - admonition
